### PR TITLE
Check for mocha dependency

### PR DESCRIPTION
**Pull request by adrigzr**
TODO:

- [ ] Fix for it to work on monorepos

### CODE REVIEW

**Comment by MisanthropicBit** [comment]
Any chance this will get merged or are there any blockers? 🙂

**Comment by adrigzr** [comment]
I found some issues that I do not remember when adding this change. Right now, I don't have time to continue with this issue, but contributions are welcome 😄

**Comment by MisanthropicBit** [comment]
That's totally fair 🙂 thanks for getting back to me so quickly. In that case, I'll pick up this issue and submit a PR. Let me know if you remember what issues you had.

**Comment by MisanthropicBit** [comment]
As far as I can tell, this was implemented in #10. Closing.

**Pull request closed without merging**
